sudo: required
services:
  - docker

before_install:
  - docker build -t tjteru/docker-react -f Dockerfile.dev .

script:
  - docker run tjteru/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  enf: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-494937358541"
  bucket_path: "docker"

  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
